p_alpha: 0.01
p_lambda: 0.001
n_in: 2
n_out: 2
dropout_in: 1.0
dropout_out: 1.0
lrate: 0.01
lrate_decay: 0.92
optimizer: 'RMSProp'
decay: 0.5
batch_size: 100
dim_in: 25
dim_out: 25
rbf_sigma: 0.1
imb_fun: 'wass'
wass_lambda: 1
wass_iterations: 10
wass_bpt: 1
use_p_correction: 1
iterations: 2000
weight_init: 0.001
outbase: 'results'
datapath: 'data/ihdp_sample.csv'
loss: 'l2'
sparse: 0
varsel: 0
save_rep: 0
output_delay: 200